title: "김태현의 블로그"
description: "GitHub Pages with Jekyll"
author: "김태현"
remote_theme: "ngzhio/jekyll-theme-hamilton"  # 원격 테마로 지정
show_downloads: false
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
